In [1]:
from sklearn.datasets import load_diabetes

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
data = load_diabetes()

In [4]:
data

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990842, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06832974, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286377, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04687948,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452837, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00421986,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [5]:
data.keys()

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])

In [6]:
data.feature_names

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [7]:
data.data          #independent data

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [8]:
data.target     #Dependent data

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [9]:
columns_name = data.feature_names

In [10]:
columns_name

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [11]:
df = pd.DataFrame(data.data, columns = columns_name)

In [12]:
df

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017282 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081414  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019908 -0.017646  
1   -0.039493 -0.068330 -0.092204  
2   -0.002592  0.002864 -0.025930  
3    0.034309  0.022692 -0.009362  
4   -0.002592 -0.031991 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018118  0.044485  
439 -0.011080 -0.046879  0.015491  
440  0.026560  0.044528 -0.025930  
441 -0.039493 -0.004220  0.003064  

[442 rows x 10 columns]

In [13]:
data.target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [14]:
df["MEDV"] = data.target

In [15]:
df

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017282 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081414  0.083740  0.027809  0.173816   

           s4        s5        s6   MEDV  
0   -0.002592  0.019908 -0.017646  151.0  
1   -0.039493 -0.068330 -0.092204   75.0  
2   -0.002592  0.002864 -0.025930  141.0  
3    0.034309  0.022692 -0.009362  206.0  
4   -0.002592 -0.031991 -0.046641  135.0  
..        ...       ...       ...    ...  
437 -0.002592  0.031193  0.007207  178.0  
438  0.034309 -0.018118  0.044485  104.0  
439 -0.011080 -0.046879  0.015491  132.0  
440  0.026560  0.044528 -0.025930  220.0  
441 -0.039493 -0.004220  0.003064   57.0  

[442 rows x 11 columns]

In [16]:
df.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6   MEDV  
0 -0.002592  0.019908 -0.017646  151.0  
1 -0.039493 -0.068330 -0.092204   75.0  
2 -0.002592  0.002864 -0.025930  141.0  
3  0.034309  0.022692 -0.009362  206.0  
4 -0.002592 -0.031991 -0.046641  135.0

In [17]:
x = df.drop("MEDV", axis = 1)  #independent variable
y = df.MEDV

In [18]:
x

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017282 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081414  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019908 -0.017646  
1   -0.039493 -0.068330 -0.092204  
2   -0.002592  0.002864 -0.025930  
3    0.034309  0.022692 -0.009362  
4   -0.002592 -0.031991 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018118  0.044485  
439 -0.011080 -0.046879  0.015491  
440  0.026560  0.044528 -0.025930  
441 -0.039493 -0.004220  0.003064  

[442 rows x 10 columns]

In [19]:
y

0      151.0
1       75.0
2      141.0
3      206.0
4      135.0
       ...  
437    178.0
438    104.0
439    132.0
440    220.0
441     57.0
Name: MEDV, Length: 442, dtype: float64

In [20]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=40)

In [21]:
x_train.shape, x_test.shape

((309, 10), (133, 10))

In [22]:
x_train

age       sex       bmi        bp        s1        s2        s3  \
161 -0.045472  0.050680  0.063852  0.070073  0.133274  0.131461 -0.039719   
27  -0.023677 -0.044642  0.059541 -0.040099 -0.042848 -0.043589  0.011824   
149 -0.049105  0.050680 -0.005128 -0.046985 -0.020832 -0.020416 -0.069172   
188  0.005383 -0.044642 -0.002973  0.049415  0.074108  0.070710  0.044958   
246  0.041708 -0.044642 -0.032073 -0.061904  0.079612  0.050982  0.056003   
..        ...       ...       ...       ...       ...       ...       ...   
306  0.009016  0.050680 -0.001895  0.021872 -0.038720 -0.024800 -0.006584   
165 -0.041840 -0.044642 -0.066563 -0.046985 -0.037344 -0.043276  0.048640   
7    0.063504  0.050680 -0.001895  0.066630  0.090620  0.108914  0.022869   
219 -0.089063 -0.044642 -0.041774 -0.019442 -0.066239 -0.074277  0.008142   
326  0.045341  0.050680 -0.008362 -0.033214 -0.007073  0.001191 -0.039719   

           s4        s5        s6  
161  0.108111  0.075738  0.085907  
27  -0.039493 -0.015998  0.040343  
149  0.071210  0.061238 -0.038357  
188 -0.002592 -0.001499 -0.009362  
246 -0.009972  0.045066 -0.059067  
..        ...       ...       ...  
306 -0.039493 -0.039810 -0.013504  
165 -0.039493 -0.056158 -0.013504  
7    0.017703 -0.035817  0.003064  
219 -0.039493  0.001144 -0.030072  
326  0.034309  0.029936  0.027917  

[309 rows x 10 columns]

In [23]:
x_train.corr()

age       sex       bmi        bp        s1        s2        s3  \
age  1.000000  0.141301  0.234150  0.332889  0.285592  0.260704 -0.095826   
sex  0.141301  1.000000  0.103081  0.217278  0.002696  0.124169 -0.383618   
bmi  0.234150  0.103081  1.000000  0.484202  0.263851  0.281320 -0.331715   
bp   0.332889  0.217278  0.484202  1.000000  0.272354  0.216779 -0.171851   
s1   0.285592  0.002696  0.263851  0.272354  1.000000  0.898255  0.099838   
s2   0.260704  0.124169  0.281320  0.216779  0.898255  1.000000 -0.174089   
s3  -0.095826 -0.383618 -0.331715 -0.171851  0.099838 -0.174089  1.000000   
s4   0.241654  0.336603  0.391250  0.275353  0.514499  0.670592 -0.732113   
s5   0.282786  0.128841  0.426549  0.420387  0.507037  0.317095 -0.344825   
s6   0.323534  0.263595  0.373092  0.478257  0.319552  0.305478 -0.249945   

           s4        s5        s6  
age  0.241654  0.282786  0.323534  
sex  0.336603  0.128841  0.263595  
bmi  0.391250  0.426549  0.373092  
bp   0.275353  0.420387  0.478257  
s1   0.514499  0.507037  0.319552  
s2   0.670592  0.317095  0.305478  
s3  -0.732113 -0.344825 -0.249945  
s4   1.000000  0.562814  0.390806  
s5   0.562814  1.000000  0.424129  
s6   0.390806  0.424129  1.000000

In [24]:
import seaborn as sns
plt.figure(figsize=(12,10))
cor = x_train.corr()
sns.heatmap(cor, annot =True)
plt.show()

In [25]:
import numpy as np
arr = np.array([[11,22,33],
                [44,55,66],
                [77,88,99]])

In [26]:
arr[1][1]

55

In [27]:
for row in range(len(arr)):
    for col in range(len(arr)):
        print(f"{arr[row][col]}")

11
22
33
44
55
66
77
88
99


In [28]:
arr1 = np.array([[11,22,33,102],
                [44,55,66,123],
                [77,88,99, 566]])

In [29]:
for i in range(len(arr1)):
    for j in range(len(arr1)+1):
        print(f"{arr1[i][j]}")

11
22
33
102
44
55
66
123
77
88
99
566


In [30]:
len(arr1)

3

In [31]:
for row in range(len(arr)):
    for col in range(row):
        print(f"{arr[row][col]}")

44
77
88


In [32]:
for i in range(len(arr)):
    for j in range(i):
        if arr[i][j] % 2 == 0:
            print(f"even element is {arr[i][j]}")

even element is 44
even element is 88


In [33]:
arr[1,2]

66

In [34]:
arr

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [35]:
arr1

array([[ 11,  22,  33, 102],
       [ 44,  55,  66, 123],
       [ 77,  88,  99, 566]])

In [36]:
def correlation(dataset, threshold):
    col_corr = set()
    corr_matrix = x_train.corr()
    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if abs(corr_matrix.iloc[i][j]) > threshold:
                colname = corr_matrix.columns[i]
                col_corr.add(colname)
    return col_corr
 
    

In [37]:
x_train.corr()

age       sex       bmi        bp        s1        s2        s3  \
age  1.000000  0.141301  0.234150  0.332889  0.285592  0.260704 -0.095826   
sex  0.141301  1.000000  0.103081  0.217278  0.002696  0.124169 -0.383618   
bmi  0.234150  0.103081  1.000000  0.484202  0.263851  0.281320 -0.331715   
bp   0.332889  0.217278  0.484202  1.000000  0.272354  0.216779 -0.171851   
s1   0.285592  0.002696  0.263851  0.272354  1.000000  0.898255  0.099838   
s2   0.260704  0.124169  0.281320  0.216779  0.898255  1.000000 -0.174089   
s3  -0.095826 -0.383618 -0.331715 -0.171851  0.099838 -0.174089  1.000000   
s4   0.241654  0.336603  0.391250  0.275353  0.514499  0.670592 -0.732113   
s5   0.282786  0.128841  0.426549  0.420387  0.507037  0.317095 -0.344825   
s6   0.323534  0.263595  0.373092  0.478257  0.319552  0.305478 -0.249945   

           s4        s5        s6  
age  0.241654  0.282786  0.323534  
sex  0.336603  0.128841  0.263595  
bmi  0.391250  0.426549  0.373092  
bp   0.275353  0.420387  0.478257  
s1   0.514499  0.507037  0.319552  
s2   0.670592  0.317095  0.305478  
s3  -0.732113 -0.344825 -0.249945  
s4   1.000000  0.562814  0.390806  
s5   0.562814  1.000000  0.424129  
s6   0.390806  0.424129  1.000000

In [39]:
corr_matrix = x_train.corr()

In [40]:
range(len(corr_matrix.columns))

range(0, 10)

In [41]:
corr_matrix.iloc[2,0]

0.23415049711775446

In [42]:
corr_matrix.columns

Index(['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6'], dtype='object')

In [43]:
corr_feature = correlation(x_train, 0.6)

In [44]:
len(set(corr_feature))

2

In [45]:
x_train.drop(corr_feature, axis = 1, inplace = True)
x_test.drop(corr_feature, axis = 1, inplace = True)

In [46]:
x_train

age       sex       bmi        bp        s1        s3        s5  \
161 -0.045472  0.050680  0.063852  0.070073  0.133274 -0.039719  0.075738   
27  -0.023677 -0.044642  0.059541 -0.040099 -0.042848  0.011824 -0.015998   
149 -0.049105  0.050680 -0.005128 -0.046985 -0.020832 -0.069172  0.061238   
188  0.005383 -0.044642 -0.002973  0.049415  0.074108  0.044958 -0.001499   
246  0.041708 -0.044642 -0.032073 -0.061904  0.079612  0.056003  0.045066   
..        ...       ...       ...       ...       ...       ...       ...   
306  0.009016  0.050680 -0.001895  0.021872 -0.038720 -0.006584 -0.039810   
165 -0.041840 -0.044642 -0.066563 -0.046985 -0.037344  0.048640 -0.056158   
7    0.063504  0.050680 -0.001895  0.066630  0.090620  0.022869 -0.035817   
219 -0.089063 -0.044642 -0.041774 -0.019442 -0.066239  0.008142  0.001144   
326  0.045341  0.050680 -0.008362 -0.033214 -0.007073 -0.039719  0.029936   

           s6  
161  0.085907  
27   0.040343  
149 -0.038357  
188 -0.009362  
246 -0.059067  
..        ...  
306 -0.013504  
165 -0.013504  
7    0.003064  
219 -0.030072  
326  0.027917  

[309 rows x 8 columns]

In [47]:
x_test

age       sex       bmi        bp        s1        s3        s5  \
192  0.056239  0.050680 -0.030996  0.008101  0.019070  0.033914 -0.029528   
337  0.019913  0.050680 -0.012673  0.070073 -0.011201 -0.039719  0.005384   
56  -0.041840 -0.044642  0.041218 -0.026328 -0.031840 -0.036038  0.033657   
9   -0.070900 -0.044642  0.039062 -0.033214 -0.012577 -0.024993  0.067736   
232  0.012648  0.050680  0.000261 -0.011409  0.039710 -0.039719  0.024053   
..        ...       ...       ...       ...       ...       ...       ...   
390  0.009016  0.050680  0.069241  0.059744  0.017694 -0.047082  0.103292   
255  0.001751 -0.044642 -0.065486 -0.005671 -0.007073  0.041277 -0.003304   
296  0.067136 -0.044642 -0.061174 -0.040099 -0.026336  0.033914 -0.056158   
273  0.074401  0.050680 -0.020218  0.045972  0.074108 -0.036038  0.106354   
369 -0.009147 -0.044642  0.037984 -0.040099 -0.024960 -0.043401 -0.005145   

           s6  
192 -0.059067  
337  0.003064  
56  -0.017646  
9   -0.013504  
232  0.032059  
..        ...  
390  0.073480  
255  0.007207  
296 -0.059067  
273  0.036201  
369  0.027917  

[133 rows x 8 columns]